[sql]
  [sql.api]#This is the connection info for the database where basic app data will be stored
    url = "postgresql://postgres@localhost:32791/Hush?sslmode=disable"
    port = 32
    type = "postgres"
  [oauth]#This is the connection info for the database where Oauth info will be stored
[server]
  port = 1234
[monitoring]
  enabled = true
  [monitoring.influx]
    enabled = false
    url = "http://localhost:8086"
