<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recruit.proto

namespace Recruit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Recruit.Person</code>
 */
class Person extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string first_name = 1;</code>
     */
    private $first_name = '';
    /**
     * <code>string last_name = 2;</code>
     */
    private $last_name = '';

    public function __construct() {
        \GPBMetadata\Recruit::initOnce();
        parent::__construct();
    }

    /**
     * <code>string first_name = 1;</code>
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * <code>string first_name = 1;</code>
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->first_name = $var;
    }

    /**
     * <code>string last_name = 2;</code>
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * <code>string last_name = 2;</code>
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_name = $var;
    }

}

