<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recruit.proto

namespace Recruit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Recruit.Recruit</code>
 */
class Recruit extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string first_name = 1;</code>
     */
    private $first_name = '';
    /**
     * <code>string last_name = 2;</code>
     */
    private $last_name = '';
    /**
     * <code>string email = 3;</code>
     */
    private $email = '';
    /**
     * <code>string phone = 4;</code>
     */
    private $phone = '';
    /**
     * <code>repeated .Recruit.Tag tags = 5;</code>
     */
    private $tags;

    public function __construct() {
        \GPBMetadata\Recruit::initOnce();
        parent::__construct();
    }

    /**
     * <code>string first_name = 1;</code>
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * <code>string first_name = 1;</code>
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->first_name = $var;
    }

    /**
     * <code>string last_name = 2;</code>
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * <code>string last_name = 2;</code>
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_name = $var;
    }

    /**
     * <code>string email = 3;</code>
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * <code>string email = 3;</code>
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;
    }

    /**
     * <code>string phone = 4;</code>
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * <code>string phone = 4;</code>
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;
    }

    /**
     * <code>repeated .Recruit.Tag tags = 5;</code>
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * <code>repeated .Recruit.Tag tags = 5;</code>
     */
    public function setTags(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Recruit\Tag::class);
        $this->tags = $arr;
    }

}

