<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recruit.proto

namespace Recruit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Recruit.Tag</code>
 */
class Tag extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 tag_id = 1;</code>
     */
    private $tag_id = 0;
    /**
     * <code>string name = 2;</code>
     */
    private $name = '';

    public function __construct() {
        \GPBMetadata\Recruit::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 tag_id = 1;</code>
     */
    public function getTagId()
    {
        return $this->tag_id;
    }

    /**
     * <code>int32 tag_id = 1;</code>
     */
    public function setTagId($var)
    {
        GPBUtil::checkInt32($var);
        $this->tag_id = $var;
    }

    /**
     * <code>string name = 2;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>string name = 2;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

}

