<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recruit.proto

namespace GPBMetadata;

class Recruit
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae2010a0d726563727569742e70726f746f12075265637275697422230a" .
            "03546167120e0a067461675f6964180120012805120c0a046e616d651802" .
            "20012809226a0a075265637275697412120a0a66697273745f6e616d6518" .
            "012001280912110a096c6173745f6e616d65180220012809120d0a05656d" .
            "61696c180320012809120d0a0570686f6e65180420012809121a0a047461" .
            "677318052003280b320c2e526563727569742e546167222f0a0650657273" .
            "6f6e12120a0a66697273745f6e616d6518012001280912110a096c617374" .
            "5f6e616d65180220012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

